// Generated by radix - do not edit

type FaberDisplayHint =
      "unknown"
    | "textus"
    | "ascii"
    | "numerus"
    | "fractus"
    | "bivalens"
    | "nihil"
    | "vacuum"
    | "valor"
    | "instans"
    | "regex"
    | { kind: "nullable"; inner: FaberDisplayHint }
    | { kind: "lista"; element: FaberDisplayHint }
    | { kind: "tensor"; element: FaberDisplayHint }
    | { kind: "sparsa"; element: FaberDisplayHint }
    | { kind: "map"; key: FaberDisplayHint; value: FaberDisplayHint }
    | { kind: "set"; element: FaberDisplayHint }
;

function __faberDisplay(value: any, hint: FaberDisplayHint = "unknown"): string {
    if (typeof hint === "object") {
        if (hint.kind === "nullable") {
            return value === null || value === undefined ? "nihil" : __faberDisplay(value, hint.inner);
        }
        if (hint.kind === "lista") { return __faberDisplayList(value, hint.element); }
        if (hint.kind === "tensor") { return __faberDisplayTensor(value, hint.element); }
        if (hint.kind === "sparsa") { return __faberDisplaySparsa(value, hint.element); }
        if (hint.kind === "map") { return __faberDisplayMap(value, hint.key, hint.value); }
        return __faberDisplayList(value, hint.element);
    }
    if (value === null || value === undefined) {
        return hint === "vacuum" ? "vacuum" : "nihil";
    }
    switch (hint) {
        case "bivalens": return value ? "verum" : "falsum";
        case "fractus": return __faberDisplayFractus(value);
        case "nihil": return "nihil";
        case "vacuum": return "vacuum";
        case "valor": return __faberDisplayValor(value);
        case "regex": return String(value);
        case "textus":
        case "ascii":
        case "instans":
        case "numerus": return String(value);
        default: return __faberDisplayValor(value);
    }
}

function __faberDisplayFractus(value: any): string {
    const n = Number(value);
    if (!Number.isFinite(n)) { return String(value); }
    return Number.isInteger(n) ? `${n}.0` : String(n);
}

function __faberDisplayList(value: any, element: FaberDisplayHint): string {
    if (value === null || value === undefined) { return "nihil"; }
    return `[${Array.from(value as Array<any>).map((item) => __faberDisplay(item, element)).join(", ")}]`;
}

function __faberDisplayTensor(value: any, element: FaberDisplayHint): string {
    if (value === null || value === undefined) { return "nihil"; }
    if (typeof value.planata === "function") { return __faberDisplayList(value.planata(), element); }
    if (Array.isArray(value.data)) { return __faberDisplayList(value.data, element); }
    return __faberDisplayValor(value);
}

function __faberDisplaySparsa(value: any, element: FaberDisplayHint): string {
    if (value === null || value === undefined) { return "nihil"; }
    if (typeof value.densata === "function") { return __faberDisplayTensor(value.densata(), element); }
    return __faberDisplayValor(value);
}

function __faberDisplayMap(value: any, keyHint: FaberDisplayHint, valueHint: FaberDisplayHint): string {
    if (value === null || value === undefined) { return "nihil"; }
    const entries = value instanceof Map ? Array.from(value.entries()) : Object.entries(value);
    return `{${entries.map(([key, item]) => `${JSON.stringify(__faberDisplay(key, keyHint))}: ${__faberDisplay(item, valueHint)}`).join(", ")}}`;
}

function __faberDisplayValor(value: any): string {
    if (value !== null && typeof value === "object" && typeof value.__faberValorTag === "string") { return __faberDisplayTaggedValor(value); }
    if (value === null || value === undefined) { return "nihil"; }
    if (typeof value === "boolean") { return value ? "verum" : "falsum"; }
    if (typeof value === "number") { return String(value); }
    if (typeof value === "string") { return value; }
    if (Array.isArray(value)) { return __faberDisplayList(value, "valor"); }
    if (typeof value.text === "function") { return String(value.text()); }
    if (typeof value.toString === "function" && value.toString !== Object.prototype.toString) { return String(value); }
    return __faberDisplayMap(value, "textus", "valor");
}

function __faberDisplayTaggedValor(value: any): string {
    const payload = value.__faberValorPayload;
    switch (value.__faberValorTag) {
        case "Nihil": return "nihil";
        case "Bivalens": return payload ? "verum" : "falsum";
        case "Numerus": return String(payload);
        case "Fractus": return __faberDisplayFractus(payload);
        case "Textus": return String(payload);
        case "Instans": return String(payload);
        case "Octeti": return `<${Array.isArray(payload) ? payload.length : 0} bytes>`;
        case "Lista": return __faberDisplayList(payload, "valor");
        case "Tabula": return __faberDisplayMap(payload, "textus", "valor");
        default: return __faberDisplayValor(payload);
    }
}

type Spatium = { tag: "html" } | { tag: "svg" };
const html: Spatium = { tag: "html" };
const svg: Spatium = { tag: "svg" };

class Attributum {
    nomen!: string;
    valor!: string;
}

class Proprietas {
    nomen!: string;
    valor!: string;
}

class Identitas {
    valor!: string;
}

class Eventum {
    nomen!: string;
}

type Visus = { tag: "Elementum", identitas: Identitas | null, spatium: Spatium, nomen_tag: string, attributa: Array<Attributum>, proprietates: Array<Proprietas>, liberi: Array<Visus> } | { tag: "Textus", valor: string } | { tag: "Fragmentum", liberi: Array<Visus> };
function Elementum(identitas: Identitas | null, spatium: Spatium, nomen_tag: string, attributa: Array<Attributum>, proprietates: Array<Proprietas>, liberi: Array<Visus>): Visus { return { tag: "Elementum", identitas, spatium, nomen_tag, attributa, proprietates, liberi }; }
function Textus(valor: string): Visus { return { tag: "Textus", valor }; }
function Fragmentum(liberi: Array<Visus>): Visus { return { tag: "Fragmentum", liberi }; }

type AppNuntius = { tag: "Incrementum", gradus: number } | { tag: "Redintegratio" };
function Incrementum(gradus: number): AppNuntius { return { tag: "Incrementum", gradus }; }
const Redintegratio: AppNuntius = { tag: "Redintegratio" };

class Vinculum {
    identitas!: string;
    eventus!: string;
    nuntius!: (p1: Eventum) => AppNuntius;
}

function textus_view(valor: string): Visus {
    return Textus(valor) as Visus;
}
function fragmentum_view(liberi: Array<Visus>): Visus {
    return Fragmentum(liberi) as Visus;
}
function elementum_view(spatium: Spatium, nomen_tag: string, liberi: Array<Visus>): Visus {
    return Elementum(null, spatium, nomen_tag, [], [], liberi) as Visus;
}
function incrementum_binding(): Vinculum {
    return Object.assign(new Vinculum(), { identitas: "contator-app", eventus: "click", nuntius: (e: Eventum): AppNuntius => Incrementum(1) as AppNuntius });
}
function contator_app(model: number): Visus {
    const attributa: Array<Attributum> = [Object.assign(new Attributum(), { nomen: "aria-label", valor: "contator" })];
    const proprietates: Array<Proprietas> = [Object.assign(new Proprietas(), { nomen: "aria-valuenow", valor: `${model}` })];
    return Elementum(nova_identitas("contator-app"), html, "div", attributa, proprietates, [textus_view("contator: "), textus_view(`${model}`), elementum_view(html, "x-metric", [textus_view(`${model}`)]), fragmentum_view([textus_view("a"), textus_view("b")])]) as Visus;
}
function nova_identitas(v: string): Identitas | null {
    return Object.assign(new Identitas(), { valor: v });
}
function contator_program(): Array<Vinculum> {
    return [incrementum_binding()];
    return [];
}
function escapa(s: string): string {
    return s;
    return "";
}
function seri_attributa(attributa: Array<Attributum>): string {
    let accum: string = "";
    for (const attr of attributa) {
        accum = (((((accum + " ") + attr.nomen) + "='") + escapa(attr.valor)) + "'");
    }
    return accum;
    return "";
}
function seri_proprietates(proprietates: Array<Proprietas>): string {
    let accum: string = "";
    for (const prop of proprietates) {
        accum = (((((accum + " data-prop:") + prop.nomen) + "='") + escapa(prop.valor)) + "'");
    }
    return accum;
    return "";
}
function seri_identitas(identitas: Identitas | null): string {
    {
        let t175: Identitas | null = ((value: Identitas | null): Identitas | null => value)(identitas);
        if (t175 === null) {
            return "";
        }
        else {
            return ((" data-tela='" + escapa((((__faberOptional: any) => __faberOptional == null ? null : __faberOptional.valor)(identitas) ?? ""))) + "'");
        }
    }
    return "";
}
function seri_ns(spatium: Spatium): string {
    {
        let t185: Spatium = ((value: Spatium): Spatium => value)(spatium);
        if (t185.tag === "html") {
            return "";
        }
        else if (t185.tag === "svg") {
            return " xmlns='http://www.w3.org/2000/svg'";
        }
        else {
            throw new Error("non-exhaustive discerne");
        }}
    return "";
}
function seri_visus(v: Visus): string {
    {
        let t268: Visus = ((value: Visus): Visus => value)(v);
        if (t268.tag === "Textus") {
            const valor = t268.valor;
            return escapa(valor);
        }
        else if (t268.tag === "Fragmentum") {
            const liberi = t268.liberi;
            let accum: string = "";
            for (const liber of liberi) {
                accum = (accum + seri_visus(liber));
            }
            return accum;
        }
        else if (t268.tag === "Elementum") {
            const identitas = t268.identitas;
            const spatium = t268.spatium;
            const nomen_tag = t268.nomen_tag;
            const attributa = t268.attributa;
            const proprietates = t268.proprietates;
            const liberi = t268.liberi;
            let accum: string = (("<" + nomen_tag) + seri_ns(spatium));
            accum = (accum + seri_attributa(attributa));
            accum = (accum + seri_proprietates(proprietates));
            accum = (accum + seri_identitas(identitas));
            let inner: string = "";
            for (const liber of liberi) {
                inner = (inner + seri_visus(liber));
            }
            return (((((accum + ">") + inner) + "</") + nomen_tag) + ">");
        }
        else {
            throw new Error("non-exhaustive discerne");
        }}
    return "";
}
class Declaratio {
    nomen!: string;
    valor!: string;
}

class Regula {
    selector!: string;
    declarationes!: Array<Declaratio>;
}

class Stilum {
    regulae!: Array<Regula>;
}

function seri_css(stilum: Stilum): string {
    let accum: string = "";
    for (const regula of stilum.regulae) {
        accum = ((accum + regula.selector) + " { ");
        for (const decl of regula.declarationes) {
            accum = ((((accum + decl.nomen) + ": ") + decl.valor) + "; ");
        }
        accum = (accum + "}\\n");
    }
    return accum;
    return "";
}
function app_arbor(): Visus {
    return contator_app(7);
}
(() => {
    {
        const html_out: string = seri_visus(app_arbor());
        const program: Array<Vinculum> = contator_program();
        const css_out: string = seri_css(Object.assign(new Stilum(), { regulae: [Object.assign(new Regula(), { selector: "[data-tela='contator-app']", declarationes: [Object.assign(new Declaratio(), { nomen: "display", valor: "grid" }), Object.assign(new Declaratio(), { nomen: "gap", valor: "0.5rem" })] })] }));
        console.log(__faberDisplay("spike arbor parata", "textus"));
    }})();
